name: never_lost
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rive: ^0.11.4
  flutter_svg: ^2.0.8
  google_fonts: ^6.1.0
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  flutter_native_splash: ^2.3.6
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_otp_text_field: ^1.1.1
  dependencies:




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter_native_splash:
  color: "#f7f671"
  color_dark: "#272727"
  image: assets/images/children_logo.jpg
  image_dark: assets/images/children_logo.jpg

  android_12:
    image: assets/images/children_logo.jpg
    icon_background_color: "#f7f671"
    image_dark: assets/images/children_logo.jpg
    icon_background_color_dark: "#272727"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
  